# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\exchange.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr_main = QtWidgets.QFrame(self.centralwidget)
        self.fr_main.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.fr_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_main.setObjectName("fr_main")
        self.lbl_amount = QtWidgets.QLabel(self.fr_main)
        self.lbl_amount.setGeometry(QtCore.QRect(20, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_amount.setFont(font)
        self.lbl_amount.setStyleSheet("color: rgb(139, 139, 139);\n"
"")
        self.lbl_amount.setObjectName("lbl_amount")
        self.txt_amount = QtWidgets.QLineEdit(self.fr_main)
        self.txt_amount.setGeometry(QtCore.QRect(20, 70, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_amount.setFont(font)
        self.txt_amount.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgb(26, 37, 255);\n"
"color: rgb(26, 37, 255);\n"
"padding-bottom: 5px;")
        self.txt_amount.setText("")
        self.txt_amount.setObjectName("txt_amount")
        self.cb_sale = QtWidgets.QComboBox(self.fr_main)
        self.cb_sale.setGeometry(QtCore.QRect(20, 150, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_sale.setFont(font)
        self.cb_sale.setAutoFillBackground(False)
        self.cb_sale.setStyleSheet("QComboBox{\n"
"border: 1px solid rgba(148, 142, 142, 0.5);\n"
"border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"border: 2px solid rgb(31, 15, 255);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"margin-right: 20px;\n"
"image: url(D:/everything/porjects/python/currency exchange app/icons/arrow.png);\n"
"}")
        self.cb_sale.setObjectName("cb_sale")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icons/usa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\icons/eu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\icons/gb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\icons/ca.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\icons/tr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\icons/ru.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\icons/ice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(".\\icons/phi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(".\\icons/den.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(".\\icons/hun.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(".\\icons/czk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(".\\icons/rom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(".\\icons/swe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(".\\icons/indo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon13, "")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(".\\icons/ind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon14, "")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(".\\icons/bra.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon15, "")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(".\\icons/cro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon16, "")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(".\\icons/jpy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon17, "")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(".\\icons/thai.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon18, "")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(".\\icons/swiss.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon19, "")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(".\\icons/mal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon20, "")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(".\\icons/bul.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon21, "")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(".\\icons/chi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon22, "")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(".\\icons/nor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon23, "")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(".\\icons/nwz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon24, "")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(".\\icons/zar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon25, "")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(".\\icons/singa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon26, "")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(".\\icons/aus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon27, "")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(".\\icons/isr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon28, "")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(".\\icons/sok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon29, "")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(".\\icons/pol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cb_sale.addItem(icon30, "")
        self.btn_convert = QtWidgets.QPushButton(self.fr_main)
        self.btn_convert.setGeometry(QtCore.QRect(20, 270, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_convert.setFont(font)
        self.btn_convert.setStyleSheet("QPushButton{\n"
"background-color: rgb(31, 15, 255);\n"
"color: #fff;\n"
"border-radius: 5px;\n"
"cursor: pointer;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(19, 12, 119);\n"
"\n"
"}")
        self.btn_convert.setObjectName("btn_convert")
        self.lbl_rate = QtWidgets.QLabel(self.fr_main)
        self.lbl_rate.setGeometry(QtCore.QRect(20, 350, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_rate.setFont(font)
        self.lbl_rate.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.lbl_rate.setStyleSheet("color: rgb(31, 15, 255);")
        self.lbl_rate.setObjectName("lbl_rate")
        self.lbl_total = QtWidgets.QLabel(self.fr_main)
        self.lbl_total.setGeometry(QtCore.QRect(20, 400, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_total.setFont(font)
        self.lbl_total.setStyleSheet("color: rgb(31, 15, 255);")
        self.lbl_total.setObjectName("lbl_total")
        self.btn_clear = QtWidgets.QPushButton(self.fr_main)
        self.btn_clear.setGeometry(QtCore.QRect(270, 70, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("border:none;\n"
"color: rgb(26, 37, 255);\n"
"")
        self.btn_clear.setObjectName("btn_clear")
        self.cb_buy = QtWidgets.QComboBox(self.fr_main)
        self.cb_buy.setGeometry(QtCore.QRect(20, 210, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_buy.setFont(font)
        self.cb_buy.setAutoFillBackground(False)
        self.cb_buy.setStyleSheet("QComboBox{\n"
"border: 1px solid rgba(148, 142, 142, 0.5);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"border: 2px solid rgb(31, 15, 255);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"margin-right: 20px;\n"
"image: url(D:/everything/porjects/python/currency exchange app/icons/arrow.png);\n"
"}")
        self.cb_buy.setObjectName("cb_buy")
        self.cb_buy.addItem(icon, "")
        self.cb_buy.addItem(icon1, "")
        self.cb_buy.addItem(icon2, "")
        self.cb_buy.addItem(icon3, "")
        self.cb_buy.addItem(icon4, "")
        self.cb_buy.addItem(icon5, "")
        self.cb_buy.addItem(icon6, "")
        self.cb_buy.addItem(icon7, "")
        self.cb_buy.addItem(icon8, "")
        self.cb_buy.addItem(icon9, "")
        self.cb_buy.addItem(icon10, "")
        self.cb_buy.addItem(icon11, "")
        self.cb_buy.addItem(icon12, "")
        self.cb_buy.addItem(icon13, "")
        self.cb_buy.addItem(icon14, "")
        self.cb_buy.addItem(icon15, "")
        self.cb_buy.addItem(icon16, "")
        self.cb_buy.addItem(icon17, "")
        self.cb_buy.addItem(icon18, "")
        self.cb_buy.addItem(icon19, "")
        self.cb_buy.addItem(icon20, "")
        self.cb_buy.addItem(icon21, "")
        self.cb_buy.addItem(icon22, "")
        self.cb_buy.addItem(icon23, "")
        self.cb_buy.addItem(icon24, "")
        self.cb_buy.addItem(icon25, "")
        self.cb_buy.addItem(icon26, "")
        self.cb_buy.addItem(icon27, "")
        self.cb_buy.addItem(icon28, "")
        self.cb_buy.addItem(icon29, "")
        self.cb_buy.addItem(icon30, "")
        self.verticalLayout.addWidget(self.fr_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_amount.setText(_translate("MainWindow", "Amount"))
        self.cb_sale.setItemText(0, _translate("MainWindow", "  USD / Dollar"))
        self.cb_sale.setItemText(1, _translate("MainWindow", "  EUR / Euro"))
        self.cb_sale.setItemText(2, _translate("MainWindow", "  GBP / Pond"))
        self.cb_sale.setItemText(3, _translate("MainWindow", "  CAD / Dollar"))
        self.cb_sale.setItemText(4, _translate("MainWindow", "  TRY / Lira"))
        self.cb_sale.setItemText(5, _translate("MainWindow", "  RUB / Ruble"))
        self.cb_sale.setItemText(6, _translate("MainWindow", "  ISK / Krone"))
        self.cb_sale.setItemText(7, _translate("MainWindow", "  PHP / Peso"))
        self.cb_sale.setItemText(8, _translate("MainWindow", "  DKK / Krone"))
        self.cb_sale.setItemText(9, _translate("MainWindow", "  HUF / Forinti"))
        self.cb_sale.setItemText(10, _translate("MainWindow", "  CZK / Krone"))
        self.cb_sale.setItemText(11, _translate("MainWindow", "  RON / Ley"))
        self.cb_sale.setItemText(12, _translate("MainWindow", "  SEK / Krone"))
        self.cb_sale.setItemText(13, _translate("MainWindow", "  IDR / Rupiah"))
        self.cb_sale.setItemText(14, _translate("MainWindow", "  INR / Rupee"))
        self.cb_sale.setItemText(15, _translate("MainWindow", "  BRL / Real"))
        self.cb_sale.setItemText(16, _translate("MainWindow", "  HRK / Kuna"))
        self.cb_sale.setItemText(17, _translate("MainWindow", "  JPY / Yen"))
        self.cb_sale.setItemText(18, _translate("MainWindow", "  THB / Baht"))
        self.cb_sale.setItemText(19, _translate("MainWindow", "  CHF / Frang"))
        self.cb_sale.setItemText(20, _translate("MainWindow", "  MYR / Ringgit"))
        self.cb_sale.setItemText(21, _translate("MainWindow", "  BGN / Leva"))
        self.cb_sale.setItemText(22, _translate("MainWindow", "  CNY / Renminbi"))
        self.cb_sale.setItemText(23, _translate("MainWindow", "  NOK / Krone"))
        self.cb_sale.setItemText(24, _translate("MainWindow", "  NZD / Dollar"))
        self.cb_sale.setItemText(25, _translate("MainWindow", "  ZAR / Rand"))
        self.cb_sale.setItemText(26, _translate("MainWindow", "  SGD / Dollar"))
        self.cb_sale.setItemText(27, _translate("MainWindow", "  AUD / Dollar"))
        self.cb_sale.setItemText(28, _translate("MainWindow", "  ILS / Sekel"))
        self.cb_sale.setItemText(29, _translate("MainWindow", "  KRW / Won"))
        self.cb_sale.setItemText(30, _translate("MainWindow", "  PLN / Zloti"))
        self.btn_convert.setText(_translate("MainWindow", "Convert"))
        self.lbl_rate.setText(_translate("MainWindow", "Rate: "))
        self.lbl_total.setText(_translate("MainWindow", "Total: "))
        self.btn_clear.setText(_translate("MainWindow", "clear"))
        self.cb_buy.setItemText(0, _translate("MainWindow", "  USD / Dollar"))
        self.cb_buy.setItemText(1, _translate("MainWindow", "  EUR / Euro"))
        self.cb_buy.setItemText(2, _translate("MainWindow", "  GBP / Pond"))
        self.cb_buy.setItemText(3, _translate("MainWindow", "  CAD / Dollar"))
        self.cb_buy.setItemText(4, _translate("MainWindow", "  TRY / Lira"))
        self.cb_buy.setItemText(5, _translate("MainWindow", "  RUB / Ruble"))
        self.cb_buy.setItemText(6, _translate("MainWindow", "  ISK / Krone"))
        self.cb_buy.setItemText(7, _translate("MainWindow", "  PHP / Peso"))
        self.cb_buy.setItemText(8, _translate("MainWindow", "  DKK / Krone"))
        self.cb_buy.setItemText(9, _translate("MainWindow", "  HUF / Forinti"))
        self.cb_buy.setItemText(10, _translate("MainWindow", "  CZK / Krone"))
        self.cb_buy.setItemText(11, _translate("MainWindow", "  RON / Ley"))
        self.cb_buy.setItemText(12, _translate("MainWindow", "  SEK / Krone"))
        self.cb_buy.setItemText(13, _translate("MainWindow", "  IDR / Rupiah"))
        self.cb_buy.setItemText(14, _translate("MainWindow", "  INR / Rupee"))
        self.cb_buy.setItemText(15, _translate("MainWindow", "  BRL / Real"))
        self.cb_buy.setItemText(16, _translate("MainWindow", "  HRK / Kuna"))
        self.cb_buy.setItemText(17, _translate("MainWindow", "  JPY / Yen"))
        self.cb_buy.setItemText(18, _translate("MainWindow", "  THB / Baht"))
        self.cb_buy.setItemText(19, _translate("MainWindow", "  CHF / Frang"))
        self.cb_buy.setItemText(20, _translate("MainWindow", "  MYR / Ringgit"))
        self.cb_buy.setItemText(21, _translate("MainWindow", "  BGN / Leva"))
        self.cb_buy.setItemText(22, _translate("MainWindow", "  CNY / Renminbi"))
        self.cb_buy.setItemText(23, _translate("MainWindow", "  NOK / Krone"))
        self.cb_buy.setItemText(24, _translate("MainWindow", "  NZD / Dollar"))
        self.cb_buy.setItemText(25, _translate("MainWindow", "  ZAR / Rand"))
        self.cb_buy.setItemText(26, _translate("MainWindow", "  SGD / Dollar"))
        self.cb_buy.setItemText(27, _translate("MainWindow", "  AUD / Dollar"))
        self.cb_buy.setItemText(28, _translate("MainWindow", "  ILS / Sekel"))
        self.cb_buy.setItemText(29, _translate("MainWindow", "  KRW / Won"))
        self.cb_buy.setItemText(30, _translate("MainWindow", "  PLN / Zloti"))
